[build]
  base = "app"
  publish = "app"
  functions = "app/netlify/functions"

[build.environment]
  NETLIFY_SKIP_SECRETS_CHECK = "true"

[functions]
  external_node_modules = ["@google-cloud/firestore", "stripe"]
  node_bundler = "esbuild"
